cache_dir: cache
output_dir: output

# Interval between rpki-client runs
interval: 1200
# Timeout before rpki-client is killed
timeout: 1175

# Deadline
# unix_timestamp(now) + deadline is passed to rpki-client process in the
# DEADLINE environment variable.
# Can be used with an rsync wrapper to timeout rsync processes.
# -1 to disable.
#
# Note that it may take ~10s before rsync is actually started
# deadline: -1

# optional: Skip or leave empty to listen on both IPv4 and IPv6
host: 0.0.0.0
port: 8888

rpki_client: /usr/sbin/rpki-client
# rsync_command: ./util/rsync_timeout

additional_opts: []
  # use -R to disable RRDP on recent rpki-client versions.

trust_anchor_locators:
  - /etc/pki/tals/afrinic.tal
  - /etc/pki/tals/apnic.tal
  - /etc/pki/tals/lacnic.tal
  - /etc/pki/tals/ripe.tal
  # You need to supply your own copy of the ARIN tal
  # If you agree to the ARIN RPA https://www.arin.net/resources/manage/rpki/tal/
  # links to the TAL at https://www.arin.net/resources/manage/rpki/arin.tal
