# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Python

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.13"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: install (dev) dependencies
        run: poetry install --with dev
      - name: lint (ruff)
        run: |
          # default set of ruff rules with GitHub Annotations
          poetry run ruff check .
      - name: lint (flak8, black)
        run: |
          poetry run flake8 rpkiclientweb tests
          poetry run black --check --diff rpkiclientweb tests
      - name: test
        run: poetry run pytest --cov rpkiclientweb --cov-report html -qq -o console_output_style=count -p no:sugar tests
      - name: package and test packaging
        run: |
          poetry build
          poetry run twine check dist/*
          poetry run check-manifest
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}-${{ matrix.python-version }}
          path: |
            dist
