# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Python

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.13"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv and set the python version
        # d9e0f98 = 6.5.0
        uses: astral-sh/setup-uv@d9e0f98d3fc6adb07d1e3d37f3043649ddad06a1
        with:
          python-version: ${{ matrix.python-version }}

      - name: lint (ruff)
        run: |
          # default set of ruff rules with GitHub Annotations
          uv run ruff check .
      - name: lint (flak8, black)
        run: |
          uv run flake8 rpkiclientweb tests
          uv run black --check --diff rpkiclientweb tests
      - name: test
        run: uv run pytest --cov rpkiclientweb --cov-report html -qq -o console_output_style=count -p no:sugar tests
      - name: package and test packaging
        run: |
          uv build
          uv run twine check dist/*
          uv run check-manifest
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}-${{ matrix.python-version }}
          path: |
            dist
